export const GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST'
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS'
export const GET_ROOMS_FAIL = 'GET_ROOMS_FAIL'
export const GET_ROOMS_RESET = 'GET_ROOMS_RESET'

export const CREATE_ROOM_REQUEST = 'CREATE_ROOM_REQUEST'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL'
export const CREATE_ROOM_RESET = 'CREATE_ROOM_RESET'

export const GET_ROOM_DETAILS_REQUEST = 'GET_ROOM_DETAILS_REQUEST'
export const GET_ROOM_DETAILS_SUCCESS = 'GET_ROOM_DETAILS_SUCCESS'
export const GET_ROOM_DETAILS_FAIL = 'GET_ROOM_DETAILS_FAIL'
export const GET_ROOM_DETAILS_RESET = 'GET_ROOM_DETAILS_RESET'

export const GET_MESSAGES_REQUEST = 'GET_MESSAGES_REQUEST'
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL'
export const GET_MESSAGES_RESET = 'GET_MESSAGES_RESET'

export const DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST'
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS'
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL'
export const DELETE_ROOM_RESET = 'DELETE_ROOM_RESET'

export const EDIT_ROOM_REQUEST = 'EDIT_ROOM_REQUEST'
export const EDIT_ROOM_SUCCESS = 'EDIT_ROOM_SUCCESS'
export const EDIT_ROOM_FAIL = 'EDIT_ROOM_FAIL'
export const EDIT_ROOM_RESET = 'EDIT_ROOM_RESET'

export const PRIVATE_MESSAGE_REQUEST = 'PRIVATE_MESSAGE_REQUEST'
export const PRIVATE_MESSAGE_SUCCESS = 'PRIVATE_MESSAGE_SUCCESS'
export const PRIVATE_MESSAGE_FAIL = 'PRIVATE_MESSAGE_FAIL'
export const PRIVATE_MESSAGE_RESET = 'PRIVATE_MESSAGE_RESET'
