export const GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST'
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS'
export const GET_ROOMS_FAIL = 'GET_ROOMS_FAIL'
export const GET_ROOMS_RESET = 'GET_ROOMS_RESET'

export const CREATE_ROOM_REQUEST = 'CREATE_ROOM_REQUEST'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL'
export const CREATE_ROOM_RESET = 'CREATE_ROOM_RESET'

export const GET_ROOM_DETAILS_REQUEST = 'GET_ROOM_DETAILS_REQUEST'
export const GET_ROOM_DETAILS_SUCCESS = 'GET_ROOM_DETAILS_SUCCESS'
export const GET_ROOM_DETAILS_FAIL = 'GET_ROOM_DETAILS_FAIL'
export const GET_ROOM_DETAILS_RESET = 'GET_ROOM_DETAILS_RESET'
