export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const REFRESH = 'REFRESH'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const DETAILS_REQUEST = 'DETAILS_REQUEST'
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS'
export const DETAILS_FAIL = 'DETAILS_FAIL'
export const DETAILS_RESET = 'DETAILS_RESET'

export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAIL = 'UPDATE_FAIL'
export const UPDATE_RESET = 'UPDATE_RESET'

export const PRIVATE_ROOMS_REQUEST = 'PRIVATE_ROOMS_REQUEST'
export const PRIVATE_ROOMS_SUCCESS = 'PRIVATE_ROOMS_SUCCESS'
export const PRIVATE_ROOMS_FAIL = 'PRIVATE_ROOMS_FAIL'
export const PRIVATE_ROOMS_RESET = 'PRIVATE_ROOMS_RESET'

export const PRIVATE_MESSAGE_REQUEST = 'PRIVATE_MESSAGE_REQUEST'
export const PRIVATE_MESSAGE_SUCCESS = 'PRIVATE_MESSAGE_SUCCESS'
export const PRIVATE_MESSAGE_FAIL = 'PRIVATE_MESSAGE_FAIL'
export const PRIVATE_MESSAGE_RESET = 'PRIVATE_MESSAGE_RESET'
